// frontend/src/components/BasicInfo.vue
<template>
  <a-descriptions bordered>
    <a-descriptions-item
        v-for="(value, key) in data"
        :key="key"
        :label="key"
        :span="3">
      {{ value }}
    </a-descriptions-item>
  </a-descriptions>
</template>

<script setup lang="ts">
defineProps<{ data: {
    filename: string;
    file_size: number;
    file_type: string;
    mime_type: string;
    md5: string;
    sha1: string;
    sha256: string;
    analyze_time: string;
  } | undefined }>();
</script>

// frontend/src/pages/analysis/result/basic-info/index.tsx
import { useRequest } from '@umijs/max';
import { Card, Descriptions, Spin } from 'antd';
import type { FC } from 'react';
import { getBasicInfo } from '../service';

const BasicInfo: FC = () => {
  const { data, loading } = useRequest(() => getBasicInfo());

  if (loading) {
    return <Spin />;
  }

  const basicInfo = data?.basic_info || {};

  return (
    <Card title="文件基本信息">
      <Descriptions column={2}>
        <Descriptions.Item label="文件名">{basicInfo.file_name}</Descriptions.Item>
        <Descriptions.Item label="文件大小">{basicInfo.file_size} 字节</Descriptions.Item>
        <Descriptions.Item label="文件类型">{basicInfo.file_type}</Descriptions.Item>
        <Descriptions.Item label="MIME类型">{basicInfo.mime_type}</Descriptions.Item>
        <Descriptions.Item label="分析时间">{basicInfo.analyze_time}</Descriptions.Item>
        <Descriptions.Item label="MD5">{basicInfo.md5}</Descriptions.Item>
        <Descriptions.Item label="SHA1">{basicInfo.sha1}</Descriptions.Item>
        <Descriptions.Item label="SHA256">{basicInfo.sha256}</Descriptions.Item>
      </Descriptions>
    </Card>
  );
};

export default BasicInfo;
